### ISSUE TITLE
求大佬更新v20

### ISSUE THREAD

**Issue by GamenRoll** [ZWolken/PingFang#2]
材料：https://github.com/ACT-02/PingFang-for-Windows

还有个细节：
apple官网和b站都是写的 
"SF Pro SC","SF Pro Text","SF Pro Icons",
**"PingFang SC"**,"Helvetica Neue","Helvetica","Arial",sans-serif

咱们字体名叫 苹方，而不是 PingFang SC，这样浏览器能fallback到“苹方”么？

**Comment by ZWolken** [comment]
[ACT-02/PingFang-for-Windows](https://github.com/ACT-02/PingFang-for-Windows)该仓库内的字体文件已经可以在Windows操作系统下正常使用，直接覆盖安装该仓库的字体文件即可。

如下图，一个字体文件可以在不同语言下同时设置不同的名称，`PingFang SC`以及`苹方-简`所指向的是同一个字体，无意外的话浏览器均可正常fallback。
![image](https://github.com/user-attachments/assets/3cb000b2-79cf-4095-8491-8c2a25aaf0c5)
