### ISSUE TITLE
HK、TC Regular字型中逗号、句号中置与靠右下不统一

### ISSUE THREAD

**Issue by gannaiju** [ZWolken/PingFang#3]
大佬你好，
在安卓手机上静读天下（版本9.4）中将字体设为PingFangHK-Regular、PingFangTC-Regular时，
会出现页面中逗号、句号的位置不统一的问题，
有些地方标点中置，而有些又靠右下。
（
[04jjs.zip](https://github.com/user-attachments/files/17140586/04jjs.zip)
![Screenshot_20240926-085208__01__01](https://github.com/user-attachments/assets/865f925f-9125-4dc6-9ad7-b312a364ef74)
![Screenshot_20240926-085644__01](https://github.com/user-attachments/assets/876f4806-1a04-4a04-9d24-3aa845dc0cc2)
PingFangSC-Regular不会出现此问题，其它字号未测试。测试时请将04jjs.zip的文件扩展名由zip改为epub）

**Comment by ZWolken** [comment]
本仓库只是单纯存档`PingFang`字体，并不会对其进行修改。
本地无法完全一致复现。
据提供的描述，有两个疑似原因：
1. `静读天下`的软件设计问题。当软件内的语言设置为简体中文时，便会出现该情况：
![Screenshot_2024-09-27-00-18-36-42_c3461c7609d9da5270f89403e887ed0e](https://github.com/user-attachments/assets/1c15c5ee-7962-445b-8efa-478c9aa1996b)
若将软件内的语言设置为繁体中文时，该情况将不会出现：
![Screenshot_2024-09-27-00-19-14-80_c3461c7609d9da5270f89403e887ed0e](https://github.com/user-attachments/assets/1d465869-541a-4287-a6bd-b34e4c171472)

2. 由于`PingFang`该字体作为OpenType类型字体，其具有Alternates（备用字体）的属性，但该属性正常情况下不会被调用
![image](https://github.com/user-attachments/assets/70aad06e-2efa-4ce5-bc8c-93fa81bd38e0)
如有需要，尝试可自行去除该属性看是否能解决问题。

**Comment by gannaiju** [comment]
谢谢大佬。经对比，应该是软件语言的设置为“系统”（手机系统为简体中文）的缘故，设为繁体中文后，问题得到解决了。
